WITH 
    EXPEDITION_DATA_0 AS(
        SELECT 'tbl_IGV0_CP_AHCAD_DOM' AS C1, MAX(EXTRACTIONDATE) AS C2 FROM STANDARD.IGV0_CP_AHCAD_DOM),
    EXPEDITION_DATA_1 AS(
        SELECT C1, C2 FROM EXPEDITION_DATA_0
        UNION ALL
        SELECT 'tbl_BGTTB_TABLON_CLIENTES_MES_TT'AS C1 ,MAX(PROCESS_DATE) AS C2 FROM DERIVATIVES_TABCLI.BGTTB_TABLON_CLIENTES_MES_TT),
    EXPEDITION_DATA_2 AS(
        SELECT C1, C2 FROM EXPEDITION_DATA_1
        UNION ALL
        SELECT 'tbl_IGV0_CP_AHCAD_M' AS C1, MAX(EXTRACTIONDATE) AS C2 FROM STANDARD.IGV0_CP_AHCAD_M),
    EXPEDITION_DATA AS(
        SELECT C1, C2 FROM EXPEDITION_DATA_2
        UNION ALL
        SELECT 'tbl_BGTMD_PB150_INICIOCONTRATACIONPRODUCTO_D'AS C1, MAX(DT) AS C2 FROM DERIVATIVES_EVBATCH.BGTMD_PB150_INICIOCONTRATACIONPRODUCTO_D)
--SELECT * FROM EXPEDITION_DATA;
SELECT
	A.Persona AS ID_URSUS,
	'JR000002' AS CODIGO_JOURNEY,
	A.FechaNacimiento AS FECHA_NACIMIENTO,
	A.TenenciaPorSerTu AS TENENCIA_XSER_TU,
	A.ClienteDigital AS CLIENTE_DIGITAL,
	C.ImporteRecursos AS IMPORTE_RECURSOS,
	B.TENENCIA_CUENTA_FACIL,
	B.TENENCIA_CUENTA_ON,
	B.NOMINA_DOMICILIADA,
	D.INGRESOS_DOMICILIADOS,
	F.CONTRATACION_CUENTA_ON,
	A.EMAIL_GESTOR AS EMAIL_GESTOR
FROM (
        SELECT
		    tabA.COPEMK AS Persona,
    		tabA.FENAC9 AS FechaNacimiento,
    		tabGestor.EMAIL_GESTOR AS EMAIL_GESTOR,
            CASE WHEN tabA.IN82MK = '1' THEN 1 ELSE 0 END AS TenenciaPorSerTu,
			CASE WHEN tabA.IN94MK = '1' THEN 1 ELSE 0 END AS ClienteDigital
		FROM STANDARD.MKTBBLON AS tabA
	    LEFT JOIN (SELECT mkg.COGSMK AS COD_GESTOR, mki.COEMAI AS EMAIL_GESTOR
	               FROM STANDARD.MKGESTOR AS mkg
	               			JOIN STANDARD.MKGESCOM AS mki
	                		ON mkg.COGSMK=mki.COGRMK
	               WHERE mkg.SNAPSHOT='LATEST'AND mki.SNAPSHOT='LATEST') AS tabGestor
	    ON tabA.COGSMK=tabGestor.COD_GESTOR
        WHERE tabA.SNAPSHOT='LATEST'
			AND ((DAY(tabA.FENAC9) = DAY(CURRENT_DATE) AND (MONTH(tabA.FENAC9) = MONTH(CURRENT_DATE) + 1) AND (YEAR(CURRENT_DATE) - YEAR(tabA.FENAC9) = '26'))
			OR  (DAY(tabA.FENAC9) = DAY(CURRENT_DATE) AND MONTH(tabA.FENAC9) = 12 AND (MONTH(CURRENT_DATE)+1) = 1 AND (YEAR(CURRENT_DATE) - YEAR(tabA.FENAC9) = '25')))
    ) AS A
	LEFT JOIN(
			  SELECT tabB.COPEMK AS Persona,
			         CASE WHEN tabB.COPSER = '10600' THEN 1 ELSE 0 END AS TENENCIA_CUENTA_FACIL,
					 CASE WHEN tabB.COPSER = '11594' THEN 1 ELSE 0 END AS TENENCIA_CUENTA_ON,
					 CASE WHEN tabB.COPSER = '11229' THEN 1 ELSE 0 END AS NOMINA_DOMICILIADA
        	  FROM STANDARD.IGV0_CP_AHCAD_DOM AS tabB
        	  WHERE tabB.EXTRACTIONDATE IN (SELECT C2 FROM EXPEDITION_DATA WHERE C1='tbl_IGV0_CP_AHCAD_DOM')--SELECT MAX(BB.EXTRACTIONDATE) FROM STANDARD.IGV0_CP_AHCAD_DOM AS BB)
							  AND tabB.COPSER IN ('10600','11594','11229')
								AND tabB.CODDMC='702' --702:DOMICILIACION OFICINA ACTUAL
  ) AS B
  	ON A.Persona = B.Persona
		LEFT JOIN(
        		SELECT tabC.CO_CODPERS_MT AS Persona, tabC.IM_SALDFINMESTOTVOLRECUR_MT AS ImporteRecursos
        		FROM DERIVATIVES_TABCLI.BGTTB_TABLON_CLIENTES_MES_TT AS tabC
        		WHERE tabC.PROCESS_DATE IN (SELECT MAX(CC.PROCESS_DATE) FROM DERIVATIVES_TABCLI.BGTTB_TABLON_CLIENTES_MES_TT AS CC)
    ) AS C
    	ON A.Persona = C.Persona
			LEFT JOIN(
        			SELECT CASE WHEN tabD.CO1504 IN ('105','151','154','135') THEN 1 ELSE 0 END AS INGRESOS_DOMICILIADOS,
							 			 tabD.COPEMK AS Persona
        			FROM STANDARD.IGV0_CP_AHCAD_M AS tabD
        			WHERE tabD.EXTRACTIONDATE IN (SELECT MAX(DD.EXTRACTIONDATE) FROM STANDARD.IGV0_CP_AHCAD_M AS DD)
    	) AS D
    		ON A.Persona = D.Persona
				LEFT JOIN(
        				SELECT CASE WHEN tabF.CO_PRODUCTO_URSUS='115594' THEN 1 ELSE 0 END AS CONTRATACION_CUENTA_ON,
											 tabF.CO_CLIENTE AS Persona
        				FROM DERIVATIVES_EVBATCH.BGTMD_PB150_INICIOCONTRATACIONPRODUCTO_D AS tabF
        				WHERE tabF.DT IN (SELECT MAX(FF.DT) FROM DERIVATIVES_EVBATCH.BGTMD_PB150_INICIOCONTRATACIONPRODUCTO_D AS FF)
								AND tabF.CO_PRODUCTO_URSUS = '115594'
    		) AS F
    			ON A.Persona = F.Persona;
