WITH 
    EXPEDITION_DATA_0 AS(
        SELECT 'tbl_BGTTB_TABLON_CLIENTES_MES_TT' AS C1, MAX(PROCESS_DATE) AS C2 FROM DERIVATIVES_TABCLI.BGTTB_TABLON_CLIENTES_MES_TT),
    EXPEDITION_DATA AS(
        SELECT C1, C2 FROM EXPEDITION_DATA_0
        UNION ALL
        SELECT 'tbl_BGTMD_PB150_INICIOCONTRATACIONPRODUCTO_D' AS C1, MAX(DT) AS C2 FROM DERIVATIVES_EVBATCH.BGTMD_PB150_INICIOCONTRATACIONPRODUCTO_D)
SELECT
A.COPEMK AS ID_URSUS,
'JR000001' AS CODIGO_JOURNEY,
A.FEPRNZ AS FECHA_VEMCIMIENTO,
A.IDCOAS  AS EMISOR_SEGURO_HOGAR,
A.COPSER AS TIPOLOGIA_SEGURO,
B.OPORTUNIDAD_GESTOR,
B.SEGURO_HOGAR_CARTERA_BANKIA,
B.DESCUENTO_SEGURO,
B.CLIENTE_RESERVA_COMERCIAL_RED,
B.CLIENTE_RESERVA_COMERCIAL_MAPFRE,
C.TENENCIA_SERVICIO_NOMINA,
C.IMULIG AS IMPORTE_NOMINA,
D.TENENCIA_SEGURO_AUTO,
D.TENENCIA_SEGURO_SALUD,
D.TENENCIA_SEGURO_DECESOS,
E.CONTRATACION_PRESTAMO_CONSUMO,
F.COMPRA_SH_CLIENTE_SINPRESTAMO,
F.COMPRA_SH_CLIENTE_PRESTAMO,
B.EMAIL_GESTOR AS EMAIL_GESTOR
FROM(
    SELECT
	        FEPRNZ,
			COPEMK,
			IDCOAS,
			COPSER
    FROM STANDARD.IGV0_SEG_POLIZAS
	WHERE SNAPSHOT='LATEST'--EXTRACTIONDATE IN (SELECT MAX(SUB_A.EXTRACTIONDATE) FROM STANDARD.IGV0_SEG_POLIZAS AS SUB_A)
	      AND COPSER IN ('43530', '43535','46100')
		  AND IDCOAS NOT IN ('018','0019','0031','0058','0063','0082','0135','0281','0386','0511','0571','0635','0676','0684','0703','0729','0755','C511','C747','0511','0650','2038','C511','C747')
		  AND FEPRNZ IS NOT NULL AND TO_DATE(FEPRNZ)=DATE_ADD(CURRENT_DATE, 56)
)AS A
    LEFT JOIN(
            SELECT
		        CASE WHEN TABLON.COGSMK = '0' THEN 0 ELSE 1 END AS OPORTUNIDAD_GESTOR,
			    CASE WHEN TABLON.INLP26 = '1' THEN 1 ELSE 0 END AS SEGURO_HOGAR_CARTERA_BANKIA,
			    CASE WHEN TABLON.IN61MK = '1' THEN 1 ELSE 0 END AS DESCUENTO_SEGURO,
			    CASE WHEN TABLON.IN77MK = '1' THEN 1 ELSE 0 END AS CLIENTE_RESERVA_COMERCIAL_RED,
			    CASE WHEN TABLON.IN16MK = '1' THEN 1 ELSE 0 END AS CLIENTE_RESERVA_COMERCIAL_MAPFRE,
			    TABLON.COPEMK,
			    tabGestor.EMAIL_GESTOR
			FROM STANDARD.MKTBBLOF AS TABLON
		    LEFT JOIN ( SELECT mkg.COGSMK AS COD_GESTOR, mki.COEMAI AS EMAIL_GESTOR
            						FROM STANDARD.MKGESTOR AS mkg
            								JOIN STANDARD.MKGESCOM AS mki
            								ON mkg.COGSMK=mki.COGRMK
            						WHERE mkg.SNAPSHOT='LATEST'AND mki.SNAPSHOT='LATEST') AS tabGestor
				ON TABLON.COGSMK=tabGestor.COD_GESTOR
				WHERE TABLON.SNAPSHOT = 'LATEST' --EXTRACTIONDATE IN (SELECT MAX(SUB_B.EXTRACTIONDATE) FROM STANDARD.MKTBBLOF AS SUB_B  WHERE SUB_B.SNAPSHOT = 'LATEST' )
		    )AS B
		    ON A.COPEMK = B.COPEMK
			LEFT JOIN(
						SELECT
						    CASE WHEN COPSER IN ( '32000', '32100') THEN 1 ELSE 0 END AS TENENCIA_SERVICIO_NOMINA,
						    IMULIG,
							COPEMK
                        FROM STANDARD.IGV0_NOM_CONTCOM 
						WHERE NOM.SNAPSHOT = 'LATEST'--NOM.EXTRACTIONDATE IN (SELECT MAX(SUB_C.EXTRACTIONDATE) FROM STANDARD.IGV0_NOM_CONTCOM AS SUB_C WHERE SUB_C.SNAPSHOT = 'LATEST')
		            ) AS C
				    ON A.COPEMK = C.COPEMK
					LEFT JOIN(
						 	    SELECT
									CASE WHEN IN_TENSEGURAUTO_MT = '1' OR IN_TENSEGURVEHISEGURAUTO_MT = '1' THEN 1 ELSE 0 END AS TENENCIA_SEGURO_AUTO,
									CASE WHEN IN_TENSEGURSALUDINDEM_MT = '1' OR IN_TENSEGURSALUDREEMB_MT= '1' OR IN_TENSEGURSALUDASISTSANIT_MT = '1' THEN 1 ELSE 0 END AS TENENCIA_SEGURO_SALUD,
									CASE WHEN IN_TENSEGUROTRSEGURDECENOPRIMUNIC_MT = '1' OR IN_TENSEGUROTRSEGURDECEPRIMUNIC_MT = '1' THEN 1 ELSE 0 END AS TENENCIA_SEGURO_DECESOS,
									CO_CLIENTE
								FROM DERIVATIVES_TABCLI.BGTTB_TABLON_CLIENTES_MES_TT
								WHERE PROCESS_DATE IN (SELECT C2 FROM EXPEDITION_DATA WHERE C1='tbl_BGTTB_TABLON_CLIENTES_MES_TT')--SELECT MAX(PROCESS_DATE) FROM DERIVATIVES_TABCLI.BGTTB_TABLON_CLIENTES_MES_TT)
                            ) AS D
					 			ON A.COPEMK = D.CO_CLIENTE
								LEFT JOIN(
								            SELECT
											    CASE WHEN INI_CONT.CO_PRODUCTO_URSUS = '11660' THEN 1 ELSE 0 END AS CONTRATACION_PRESTAMO_CONSUMO,
												INI_CONT.CO_CLIENTE
											FROM DERIVATIVES_EVBATCH.BGTMD_PB150_INICIOCONTRATACIONPRODUCTO_D AS INI_CONT
											WHERE INI_CONT.DT IN (SELECT C2 FROM EXPEDITION_DATA WHERE C1='tbl_BGTMD_PB150_INICIOCONTRATACIONPRODUCTO_D')--SELECT MAX(SUB_E.DT) FROM DERIVATIVES_EVBATCH.BGTMD_PB150_INICIOCONTRATACIONPRODUCTO_D AS SUB_E )
										          AND INI_CONT.CO_PRODUCTO_URSUS = '11660'
												  AND INI_CONT.CO_EMPRESA_CONT = '0'
								        ) AS E
								        ON A.COPEMK = E.CO_CLIENTE
										LEFT JOIN(
										        SELECT  DP.CO_CLIENTE CO_CLIENTE,
											 			CASE WHEN DP.MODELID = 'MSGHCHX1' THEN DP.PROBA ELSE 0 END AS COMPRA_SH_CLIENTE_SINPRESTAMO,
                                                        CASE WHEN DP.MODELID = 'MSGHSHX1' THEN DP.PROBA ELSE 0 END AS COMPRA_SH_CLIENTE_PRESTAMO
                                                        FROM(
										               	              SELECT CO_CLIENTE,
										               	                     MODELID,
										               	                     MAX(PROBABILIDAD) AS PROBA
														              FROM DERIVATIVES_MODELS_IN.BGMD_IN_MATRIZ_PROPENSIONES
														              WHERE MODELID IN ('MSGHCHX1', 'MSGHSHX1')
														              GROUP BY CO_CLIENTE, MODELID
														 )AS DP
										        ) AS F
										 		ON A.COPEMK = F.CO_CLIENTE
GROUP BY 
A.COPEMK,
A.FEPRNZ,
A.IDCOAS,
A.COPSER,
B.OPORTUNIDAD_GESTOR,
B.SEGURO_HOGAR_CARTERA_BANKIA,
B.DESCUENTO_SEGURO,
B.CLIENTE_RESERVA_COMERCIAL_RED,
B.CLIENTE_RESERVA_COMERCIAL_MAPFRE,
C.TENENCIA_SERVICIO_NOMINA,
C.IMULIG,
D.TENENCIA_SEGURO_AUTO,
D.TENENCIA_SEGURO_SALUD,
D.TENENCIA_SEGURO_DECESOS,
E.CONTRATACION_PRESTAMO_CONSUMO,
F.COMPRA_SH_CLIENTE_SINPRESTAMO,
F.COMPRA_SH_CLIENTE_PRESTAMO,
B.EMAIL_GESTOR;
